
(()=>{
 const root=document.getElementById('thk-green');
 const find=id=>root.querySelector('#'+id);
 const data={
  pillars:[
   {name:'Parahyangan',relation:'Hubungan manusia dengan Tuhan',title:'Parahyangan 🙏',summary:'Hubungan harmonis antara manusia dengan Tuhan.',examples:['Berdoa','Beribadah','Menjalankan ajaran agama'],image:'Prahyangan/photo-1552301726-570d51466ae2.avif',alt:'Umat berdoa di depan pancuran air saat ritual melukat di Bali',position:'50% 50%',paragraphs:['Parahyangan berbicara tentang keharmonisan hubungan manusia dengan Tuhan. Dalam kehidupan masyarakat Hindu Bali, hubungan ini hadir melalui doa, rasa syukur, dan praktik keagamaan.','Penerapannya bukan hanya tentang upacara. Kesadaran untuk menghormati kehidupan dan menjalankan keyakinan dengan tulus juga memberi ruang bagi hubungan spiritual.'],practice:'Luangkan waktu hening untuk berdoa sesuai keyakinan dan mensyukuri satu hal sederhana hari ini.'},
   {name:'Pawongan',relation:'Hubungan manusia dengan sesama',title:'Pawongan 🤝',summary:'Hubungan harmonis antara manusia dengan sesama.',examples:['Saling menghargai','Membantu satu sama lain','Bekerja sama','Menjaga kerukunan'],image:'Prahyangan/photo-1641082918149-24470fe02c39.avif',alt:'Sekelompok orang mengikuti kegiatan melukat bersama di kolam pancuran Bali',position:'50% 50%',paragraphs:['Pawongan menekankan hubungan yang harmonis antarmanusia. Kehidupan bersama membutuhkan rasa saling menghormati, komunikasi, dan kemauan untuk bekerja sama.','Gotong royong menjadi contoh yang mudah ditemui. Setiap orang memberi kontribusi sesuai kemampuan, dengan kepentingan bersama sebagai tujuan.'],practice:'Tawarkan bantuan kepada seseorang di sekitarmu atau luangkan waktu untuk benar-benar mendengarkan ceritanya.'},
   {name:'Palemahan',relation:'Hubungan manusia dengan lingkungan',title:'Palemahan 🌱',summary:'Hubungan harmonis antara manusia dengan lingkungan.',examples:['Menjaga kebersihan','Membuang sampah pada tempatnya','Merawat tanaman','Menjaga alam'],image:'assets/images/hero-user.jpg',alt:'Sawah berundak yang dikelilingi pepohonan hijau di Bali',position:'50% 55%',paragraphs:['Palemahan mengajak manusia menjaga hubungan yang harmonis dengan lingkungan. Alam mendukung kehidupan melalui air, pangan, udara, dan ruang untuk tumbuh.','Menghemat sumber daya serta merawat lingkungan dapat dimulai dari rumah. Kebiasaan kecil yang dilakukan bersama membantu menjaga keseimbangan.'],practice:'Bawa botol minum sendiri dan perhatikan satu kebiasaan yang bisa mengurangi pemborosan air hari ini.'}
  ],
  quiz:[
   {question:'Bergotong royong bersama tetangga terutama mencerminkan hubungan apa?',options:['Manusia dengan Tuhan','Manusia dengan sesama','Manusia dengan alam'],correct:1,explanation:'Kerja sama antarmanusia mencerminkan Pawongan. Jika dilakukan untuk merawat lingkungan, kegiatan yang sama juga mendukung Palemahan.'},
   {question:'Pilar apa yang menekankan hubungan spiritual manusia dengan Tuhan?',options:['Parahyangan','Pawongan','Palemahan'],correct:0,explanation:'Parahyangan berfokus pada hubungan manusia dengan Tuhan, termasuk melalui doa dan rasa syukur.'},
   {question:'Kebiasaan mana yang paling langsung mencerminkan Palemahan?',options:['Mendengarkan cerita teman','Menghemat penggunaan air','Meluangkan waktu untuk berdoa'],correct:1,explanation:'Menggunakan air dengan bijak merupakan salah satu cara merawat lingkungan, sesuai nilai Palemahan.'}
  ]
 };
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const design={motion:'flow',appearance:'auto'};
 function animate(node,frames,duration=600){if(reduced.matches||design.motion==='off'||!node.animate)return null;node.getAnimations().forEach(a=>a.cancel());return node.animate(frames,{duration:design.motion==='gentle'?duration*.75:duration,easing:'cubic-bezier(.22,1,.36,1)'});}
 const element=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 function icon(name){const i=element('i','fa-solid fa-'+name);i.setAttribute('aria-hidden','true');return i;}
 const tabs=Array.from(root.querySelectorAll('.g-tab'));
 let selected=0;
 function selectPillar(index,withMotion=true){selected=index;const p=data.pillars[index];tabs.forEach((tab,i)=>{tab.setAttribute('aria-selected',String(i===index));tab.tabIndex=i===index?0:-1;});root.querySelector('.g-tabs').style.setProperty('--selected',index);find('g-panel').setAttribute('aria-labelledby','g-tab-'+index);find('g-relation').textContent=p.relation;find('g-panel-title').textContent=p.title;find('g-panel-summary').textContent=p.summary;find('g-panel-img').src=p.image;find('g-panel-img').alt=p.alt;find('g-panel-img').style.objectPosition=p.position;find('g-examples').replaceChildren(...p.examples.map(text=>{const line=element('li','g-example');line.append(icon('check'),document.createTextNode(text));return line;}));find('g-read').setAttribute('aria-label','Selami makna '+p.name);if(withMotion){animate(find('g-panel-body'),[{opacity:.15,transform:'translateY(13px)'},{opacity:1,transform:'translateY(0)'}]);animate(find('g-panel-img'),[{opacity:.6,transform:'scale(1.045)'},{opacity:1,transform:'scale(1)'}],850);}}
 tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>{if(i!==selected)selectPillar(i);});tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%3;if(e.key==='ArrowLeft')next=(i+2)%3;if(e.key==='Home')next=0;if(e.key==='End')next=2;if(next!==undefined){e.preventDefault();selectPillar(next);tabs[next].focus();}});});
 selectPillar(0,false);
 const dialog=find('g-dialog');let closing=false;
 find('g-read').addEventListener('click',()=>{const p=data.pillars[selected];find('g-dialog-title').textContent=p.name;find('g-dialog-relation').textContent=p.relation;find('g-dialog-copy').replaceChildren(...p.paragraphs.map(text=>element('p','g-detail-copy',text)));find('g-practice').textContent=p.practice;dialog.showModal();animate(dialog,[{opacity:0,transform:'translateY(24px) scale(.96)'},{opacity:1,transform:'translateY(0) scale(1)'}],500);});
 async function closeDialog(){if(closing)return;closing=true;const a=animate(dialog,[{opacity:1,transform:'translateY(0) scale(1)'},{opacity:0,transform:'translateY(12px) scale(.98)'}],220);if(a)await a.finished.catch(()=>{});dialog.close();closing=false;}
 find('g-close').addEventListener('click',closeDialog);dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog();});
 const menu=find('g-menu'),nav=find('g-navigation');
 menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Tutup':'Menu';nav.classList.toggle('g-open',open);if(open)animate(nav,[{opacity:0,transform:'translateY(-6px)'},{opacity:1,transform:'translateY(0)'}],350);});
 nav.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('g-open');menu.setAttribute('aria-expanded','false');menu.textContent='Menu';menu.focus();}});
 root.querySelectorAll('a[href^="#g-"]').forEach(link=>link.addEventListener('click',e=>{const target=root.querySelector(link.getAttribute('href'));if(!target)return;e.preventDefault();nav.classList.remove('g-open');menu.setAttribute('aria-expanded','false');menu.textContent='Menu';if(!target.hasAttribute('tabindex'))target.tabIndex=-1;target.focus({preventScroll:true});target.scrollIntoView({behavior:reduced.matches||design.motion==='off'?'instant':'smooth',block:'start'});}));
 let step=0,score=0,answered=false;
 function updateProgress(done){find('g-step').textContent=step<data.quiz.length?'Pertanyaan '+(step+1)+' dari '+data.quiz.length:'Kuis selesai';find('g-score').textContent='Skor '+score;find('g-progress').setAttribute('aria-valuenow',done);find('g-progress-fill').style.transform='scaleX('+(done/data.quiz.length)+')';}
 function renderQuestion(withMotion=false){answered=false;const q=data.quiz[step];updateProgress(step);const body=find('g-question-body');body.replaceChildren();const heading=element('h3','g-question',q.question),answers=element('div','g-answers'),feedback=element('p','g-feedback');feedback.hidden=true;feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite');const next=element('button','g-action g-next',step===data.quiz.length-1?'Lihat hasil':'Pertanyaan berikutnya');next.type='button';next.disabled=true;next.append(icon('arrow-right'));q.options.forEach((text,i)=>{const b=element('button','g-answer');b.type='button';b.append(element('span','g-answer-letter',String.fromCharCode(65+i)),element('span','',text));b.addEventListener('click',()=>{if(answered)return;answered=true;const correct=i===q.correct;if(correct)score++;Array.from(answers.children).forEach((option,index)=>{option.disabled=true;if(index===q.correct){option.dataset.state='correct';option.append(element('span','g-answer-status','✓ Benar'));}else if(index===i){option.dataset.state='wrong';option.append(element('span','g-answer-status','Pilihanmu'));}});feedback.hidden=false;feedback.textContent=(correct?'Tepat! ':'Belum tepat. ')+q.explanation;animate(feedback,[{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],450);animate(b,[{transform:'scale(.985)'},{transform:'scale(1)'}],350);next.disabled=false;updateProgress(step+1);next.focus({preventScroll:true});});answers.append(b);});next.addEventListener('click',()=>{step++;if(step===data.quiz.length)renderResult();else renderQuestion(true);find('g-question-body').querySelector('button').focus({preventScroll:true});});body.append(heading,answers,feedback,next);if(withMotion)animate(body,[{opacity:0,transform:'translateX(18px)'},{opacity:1,transform:'translateX(0)'}],500);}
 function renderResult(){updateProgress(data.quiz.length);const body=find('g-question-body');body.replaceChildren();body.append(element('h3','g-question',score===data.quiz.length?'Kamu sudah mengenal ketiganya.':'Terus jelajahi, terus belajar.'),element('p','g-result-number',score+' / '+data.quiz.length),element('p','g-detail-copy','Jawaban benar. Pilih satu kebiasaan baik dan bawa ke harimu.'));const retry=element('button','g-action g-next','Ulangi kuis');retry.type='button';retry.append(icon('rotate-right'));retry.addEventListener('click',()=>{step=0;score=0;renderQuestion(true);find('g-question-body').querySelector('button').focus({preventScroll:true});});body.append(retry);animate(body,[{opacity:0,transform:'translateY(15px)'},{opacity:1,transform:'translateY(0)'}],700);}
 renderQuestion();
 if('IntersectionObserver'in window&&!reduced.matches){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.remove('g-pending');observer.unobserve(entry.target);}});},{threshold:.06});root.querySelectorAll('.g-reveal').forEach(n=>{n.classList.add('g-pending');observer.observe(n);});}
 function updateMotion(){root.style.colorScheme=design.appearance==='auto'?'':design.appearance;root.style.setProperty('--g-duration',design.motion==='off'?'0ms':design.motion==='gentle'?'450ms':'650ms');root.querySelectorAll('.g-pending').forEach(n=>n.classList.remove('g-pending'));root.dataset.motion=design.motion;if(design.motion==='off')root.getAnimations({subtree:true}).forEach(a=>a.cancel());}
 if(globalThis.Tweak){const tweak=new Tweak({container:root,onChange:updateMotion});tweak.addSelect(design,'appearance',{label:'Tampilan hijau',options:[{label:'Ikuti perangkat',value:'auto'},{label:'Hijau terang',value:'light'},{label:'Hijau hutan gelap',value:'dark'}]});tweak.addSelect(design,'motion',{label:'Gerakan',options:[{label:'Mengalir',value:'flow'},{label:'Lebih tenang',value:'gentle'},{label:'Tanpa animasi',value:'off'}]});}
})();
